### ISSUE TITLE
Improve UPM package

### ISSUE THREAD

**Issue by favoyang** [grownith/jmespath.upm#1]
Hi @Thaina,

Thanks for creating the amazing project. I'm the creator of [OpenUPM](https://openupm.com), a public upm registry with automatic build pipelines that publish new package bundle based on valid git tags. You can read [the announcement](https://www.patreon.com/posts/openupm-beta-is-32544176) to get the basic idea, so far it hosts 80+ packages as of December 2019.

I would like to [include this package](https://openupm.com/packages/add/) if
- A license file is added
- Make a [GitHub Release](https://github.com/Thaina/jmespath.upm/releases) for v0.0.1

**Comment by Thaina** [comment]
@favoyang I don't know how to write license file. I don't have any demand for using this package. In fact I made this package by copying all code from https://github.com/jdevillard/JmesPath.Net so could you please suggest me what should I do?

**Comment by favoyang** [comment]
The correct way is that put [JmesPath.Net's LICENSE](https://github.com/jdevillard/JmesPath.Net/blob/master/LICENSE) to your root path, which is Apache-2.0 license. Since your work is based on jdevillard's work.

Then please make a [GitHub Release](https://github.com/Thaina/jmespath.upm/releases) for v0.0.1

**Comment by Thaina** [comment]
@favoyang Is it like this?

**Comment by favoyang** [comment]
Thanks for your efforts. The package has been processing correctly at https://openupm.com/packages/com.devlab.jmespath/

You can also [add a badge](https://openupm.com/docs/adding-upm-package.html), like this to README

[![openupm](https://img.shields.io/npm/v/com.devlab.jmespath?label=openupm&registry_uri=https://package.openupm.com)](https://openupm.com/packages/com.devlab.jmespath/)

Feel free to close the issue, and happy coding!
